# Generated by Django 3.1.2 on 2020-10-29 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0004_auto_20201026_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill_selected',
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice_logs.profile'),
        ),
    ]
