# Generated by Django 3.1.2 on 2020-11-05 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice_logs', '0006_auto_20201102_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
        migrations.CreateModel(
            name='Skill_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('skill', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='practice_logs.skill')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
