# Generated by Django 3.1.2 on 2020-11-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0005_auto_20201028_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='practice_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='practice_hours',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_hours',
        ),
    ]
