# Generated by Django 3.1.2 on 2020-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0007_auto_20201105_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_entry',
            name='hours_practiced',
            field=models.IntegerField(default=0),
        ),
    ]
