# Generated by Django 3.1.2 on 2020-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_logs', '0008_skill_entry_hours_practiced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='skill_entry',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_entry',
            field=models.ManyToManyField(to='practice_logs.Skill_Entry'),
        ),
    ]
